project: AuthKeeper.xcodeproj
#retain_objc_accessible: true
#retain_assign_only_properties: true
#retain_public: true
#external_encodable_protocol:true

schemes:
- AuthKeeper
- DomainLayer
- DataLayer
- Models
targets:
- AuthKeeper
#verbose: false
#skip_build: false
format: xcode
